FROM python:3.11.0-bullseye

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -qqy && apt-get install -qqy \
  make \
  clang \
  curl \
  gcc \
  g++ \
  libgsl-dev \
  swig \
  autoconf
RUN python3 -m pip install numpy pandas scipy pytest

COPY tests/requirements.txt /requirements.txt
RUN python3 -m pip install -r /requirements.txt

COPY . /OpenABM-Covid19

WORKDIR /OpenABM-Covid19
RUN autoconf && ./configure
RUN make clean && make install

WORKDIR /OpenABM-Covid19
ENTRYPOINT ["/usr/local/bin/pytest", "-vv"]
